[package]
name = "day07"
version = "1.0.0"
authors = ["Eduardo SÃ¡nchez <whipshout@gmail.com>"]
description = "Day 02 of advent of code 2021"
edition = "2021"

[lib]
path = "src/lib/mod.rs"

[dependencies]
tools = { path = "../tools" }